AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Diagnostico medico

Resources:
  DiagnosisAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./app
      Handler: main.handler
      Runtime: python3.9
      Events:
        DiagnosisEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref DiagnosisApiGateway
            Path: /api/v1/diagnosis
            Method: POST

  DiagnosisApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: DiagnosisApi
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Value: !Sub "https://${DiagnosisApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"